version: '3'

services:
  postgres:
    image: postgres:12
    tty: true
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=development
